language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd udagram-user-api
  - docker build -t udagram-user-api-image1 .
  - docker tag udagram-user-api-image1 shahjuhi1108/udagram-user-api-image1:latest
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shahjuhi1108/udagram-user-api-image1

